/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techquiz.gui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import techquiz.dao.QuestionDao;
import techquiz.pojo.Answer;
import techquiz.pojo.ExamPojo;
import techquiz.pojo.QuestionPojo;
import techquiz.pojo.QuestionStore;

/**
 *
 * @author DELL
 */
public class EditQuestionFrame extends javax.swing.JFrame {

    public EditQuestionFrame(ExamPojo newexam) {
        this();
        this.newexam = newexam;
        lblTitle.setText(newexam.getLanguage());
        qno=1;
        lblQuestionno.setText("QUESTION NO:"+qno);
        qstore=new QuestionStore();
        
        loadQuestions();
        showQuestion();
       
    }

    ExamPojo newexam;
    QuestionStore qstore;
    QuestionStore newqstore;
    private String Question,option1,option2,option3,option4,correctoption;
    int qno;
    int pos=0;
    private HashMap<String,String>options;
    
    public EditQuestionFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        options=new HashMap<>();
        options.put("option1", "Answer1");
        options.put("option2", "Answer2");
        options.put("option3", "Answer3");
        options.put("option4", "Answer4");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblQuestionno = new javax.swing.JLabel();
        txtQuestion = new javax.swing.JTextField();
        lbloption1 = new javax.swing.JLabel();
        lbloption2 = new javax.swing.JLabel();
        lbloption3 = new javax.swing.JLabel();
        lbloption4 = new javax.swing.JLabel();
        txtoption1 = new javax.swing.JTextField();
        txtoption3 = new javax.swing.JTextField();
        txtoption2 = new javax.swing.JTextField();
        txtoption4 = new javax.swing.JTextField();
        btnnext = new javax.swing.JButton();
        btndone = new javax.swing.JButton();
        lblcorrectoption = new javax.swing.JLabel();
        jccorrectoption = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 21, 139, 23));

        lblQuestionno.setForeground(new java.awt.Color(51, 51, 51));
        lblQuestionno.setOpaque(true);
        jPanel1.add(lblQuestionno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, 21));

        txtQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuestionActionPerformed(evt);
            }
        });
        jPanel1.add(txtQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 72, 470, 55));

        lbloption1.setBackground(new java.awt.Color(0, 0, 0));
        lbloption1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbloption1.setForeground(new java.awt.Color(0, 0, 255));
        lbloption1.setText("option1");
        jPanel1.add(lbloption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 51, -1));

        lbloption2.setBackground(new java.awt.Color(0, 0, 0));
        lbloption2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbloption2.setForeground(new java.awt.Color(0, 0, 204));
        lbloption2.setText("option2");
        jPanel1.add(lbloption2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 50, 10));

        lbloption3.setBackground(new java.awt.Color(0, 0, 0));
        lbloption3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbloption3.setForeground(new java.awt.Color(0, 0, 204));
        lbloption3.setText("option3");
        jPanel1.add(lbloption3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 51, -1));

        lbloption4.setBackground(new java.awt.Color(0, 0, 0));
        lbloption4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbloption4.setForeground(new java.awt.Color(0, 0, 153));
        lbloption4.setText("option4");
        jPanel1.add(lbloption4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 51, -1));
        jPanel1.add(txtoption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 67, -1));

        txtoption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoption3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtoption3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 67, -1));
        jPanel1.add(txtoption2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 67, -1));
        jPanel1.add(txtoption4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 67, -1));

        btnnext.setText("NEXT");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });
        jPanel1.add(btnnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        btndone.setText("DONE");
        btndone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoneActionPerformed(evt);
            }
        });
        jPanel1.add(btndone, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        lblcorrectoption.setBackground(new java.awt.Color(0, 0, 0));
        lblcorrectoption.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblcorrectoption.setForeground(new java.awt.Color(0, 0, 204));
        lblcorrectoption.setText("correctOption");
        jPanel1.add(lblcorrectoption, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 80, -1));

        jccorrectoption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "option1", "option2", "option3", "option4" }));
        jPanel1.add(jccorrectoption, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 490));

        jMenu1.setText("Back");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuestionActionPerformed

    private void txtoption3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoption3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoption3ActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
       
        
                if(validateInput()==false)
        {
            JOptionPane.showMessageDialog(null, "Please fill all the input fields","Cannot Add Question!",JOptionPane.ERROR_MESSAGE);
            return;
        }
               String optionName=options.get(correctoption);
        QuestionPojo obj=new QuestionPojo(newexam.getExamId(),qno,newexam.getLanguage(),option1,option2,option3,option4,optionName, Question);

         System.out.println(obj);
         System.out.println(pos);
         qstore.removeQuestion(pos);
         qstore.setQuestionAt(pos, obj);
        
        ++pos;
        if(pos>=qstore.getCount())
        {
            pos=0;
        }
         ++qno;         
        if(qno>qstore.getCount())
                qno=1;
        lblQuestionno.setText("Question no:"+qno);
        showQuestion();
       
    }//GEN-LAST:event_btnnextActionPerformed

    private void btndoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoneActionPerformed
        try {
            QuestionDao.updateQuestions(newexam.getExamId());
            QuestionDao.addQuestion(qstore);
            
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(null, "Error while connecting to DB!","Exception!",JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
                return;
        }
          JOptionPane.showMessageDialog(null, "your question set is updated","update succesful!",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btndoneActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
       EditPaperFrame e=new EditPaperFrame();
       e.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditQuestionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditQuestionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditQuestionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditQuestionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditQuestionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndone;
    private javax.swing.JButton btnnext;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jccorrectoption;
    private javax.swing.JLabel lblQuestionno;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblcorrectoption;
    private javax.swing.JLabel lbloption1;
    private javax.swing.JLabel lbloption2;
    private javax.swing.JLabel lbloption3;
    private javax.swing.JLabel lbloption4;
    private javax.swing.JTextField txtQuestion;
    private javax.swing.JTextField txtoption1;
    private javax.swing.JTextField txtoption2;
    private javax.swing.JTextField txtoption3;
    private javax.swing.JTextField txtoption4;
    // End of variables declaration//GEN-END:variables





public void loadQuestions(){
 
        try{
                ArrayList<QuestionPojo> questionList=QuestionDao.getQuestionsByExamid(newexam.getExamId());
                for(QuestionPojo obj:questionList){
                    qstore.addQuestion(obj);
                    System.out.println(obj);
                }
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Error while connecting to DB!","Exception!",JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }

}

      public void showQuestion(){

                QuestionPojo question=qstore.getQuestion(pos);
                System.out.println(pos);
                System.out.println(qstore.getCount());
                 System.out.println(question);
        clearAll();
        txtQuestion.setText(question.getQuestion());
          System.out.println(question.getQuestion());
        txtoption1.setText(question.getAnswer1());
        txtoption2.setText(question.getAnswer2());
        txtoption3.setText(question.getAnswer3());
        txtoption4.setText(question.getAnswer4());
       String correctanswer=question.getCorrectAnswer();
        switch(correctanswer){
            case "Answer1":
                jccorrectoption.setSelectedIndex(0);
                break;
            case "Answer2":
                jccorrectoption.setSelectedIndex(1);
                break;
            case "Answer3":
                jccorrectoption.setSelectedIndex(2);
                break;
            case "Answer4":
                jccorrectoption.setSelectedIndex(3);
                break;
        }

        
    }

       public void clearAll(){
        
        txtQuestion.setText("");
        txtoption1.setText("");
         txtoption2.setText("");
          txtoption3.setText("");
           txtoption4.setText("");
           jccorrectoption.setSelectedIndex(0);
           
        
    }
      
       public boolean validateInput(){
        Question=txtQuestion.getText().trim();
        option1=txtoption1.getText().trim();
         option2=txtoption2.getText().trim();
          option3=txtoption3.getText().trim();
           option4=txtoption4.getText().trim();
           correctoption=jccorrectoption.getSelectedItem().toString();
           System.out.println(correctoption);
           if(Question.isEmpty()||option1.isEmpty()||option2.isEmpty()||option3.isEmpty()||option4.isEmpty())
               return false;
           else
               return true;
        
    }
      
      
}
