/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techquiz.gui;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import techquiz.dao.PerformanceDao;
import techquiz.pojo.StudentScore;
import techquiz.pojo.UserProfile;

/**
 *
 * @author DELL
 */
public class ViewSingleScoreFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllScoresFrame
     */
    public ViewSingleScoreFrame() {
        initComponents();
                this.setLocationRelativeTo(null);
        lblUsername.setText("Hello "+UserProfile.getUsername());
        loadStudentId();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLanguage = new javax.swing.JTextField();
        txtPercentage = new javax.swing.JTextField();
        jcStudentid = new javax.swing.JComboBox<>();
        jcExamid = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Student Score Panel");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 194, 26));

        lblUsername.setBackground(new java.awt.Color(0, 0, 0));
        lblUsername.setForeground(new java.awt.Color(255, 255, 51));
        jPanel1.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 11, 56, 13));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Log out");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 60, 26));

        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Select student");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 77, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Exam id");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 75, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("language");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 61, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("percentage");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 77, 30));

        txtLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLanguageActionPerformed(evt);
            }
        });
        jPanel1.add(txtLanguage, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 71, -1));

        txtPercentage.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(txtPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 76, -1));

        jcStudentid.setForeground(new java.awt.Color(204, 204, 0));
        jcStudentid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcStudentidItemStateChanged(evt);
            }
        });
        jPanel1.add(jcStudentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 66, -1));

        jcExamid.setForeground(new java.awt.Color(204, 204, 0));
        jcExamid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcExamidItemStateChanged(evt);
            }
        });
        jPanel1.add(jcExamid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 66, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        jMenu1.setText("Back");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLanguageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLanguageActionPerformed

    private void jcStudentidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcStudentidItemStateChanged
        String studentid=jcStudentid.getSelectedItem().toString();
       try{
       ArrayList<String> examidlist=PerformanceDao.getAllExamid(studentid);
       for(String examid:examidlist)
           jcExamid.addItem(examid);
       
       }
        catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Error while connecting to DB!","Exception!",JOptionPane.ERROR_MESSAGE); 
                ex.printStackTrace();

    }//GEN-LAST:event_jcStudentidItemStateChanged
    }
    private void jcExamidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcExamidItemStateChanged
        
   String studentid=jcStudentid.getSelectedItem().toString();
        String examid=jcExamid.getSelectedItem().toString();
        try{
            StudentScore obj=PerformanceDao.getScore(studentid, examid);
             txtLanguage.setText(obj.getLanguage());
            txtPercentage.setText(String.valueOf(obj.getPer()));
        }
        
        catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Error while connecting to DB!","Exception!",JOptionPane.ERROR_MESSAGE); 
                ex.printStackTrace();
       
    }//GEN-LAST:event_jcExamidItemStateChanged
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ViewScoresFrame v=new ViewScoresFrame();
       v.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSingleScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSingleScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSingleScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSingleScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSingleScoreFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcExamid;
    private javax.swing.JComboBox<String> jcStudentid;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtLanguage;
    private javax.swing.JTextField txtPercentage;
    // End of variables declaration//GEN-END:variables

    public void loadStudentId(){
        
         
        try{
       ArrayList<String> studentIdList=PerformanceDao.getAllStudentid();
           if(studentIdList.size()==0)
         JOptionPane.showMessageDialog(null, "No Student have appeared for examination!","students havent appeared yet",JOptionPane.INFORMATION_MESSAGE); 
           else { 
               for(String studentid:studentIdList)
               jcStudentid.addItem(studentid);
        }
        }
          catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Error while connecting to DB!","Exception!",JOptionPane.ERROR_MESSAGE); 
                ex.printStackTrace();
            }
        
}

}
